# Generated by Django 5.1.4 on 2025-10-04 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0019_rename_is_favorite_executive_is_favourite'),
        ('payments', '0003_userrecharge'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedemptionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Fixed redemption amount available for executives (e.g., 500, 1000)', max_digits=12, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this option available?')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['amount'],
            },
        ),
        migrations.CreateModel(
            name='ExecutivePayoutRedeem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Final amount approved by admin', max_digits=12, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('executive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_redeems', to='executives.executive')),
                ('redemption_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redeem_requests', to='payments.redemptionoption')),
            ],
        ),
    ]
