# Generated by Django 5.1.4 on 2025-10-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_redemptionoption_executivepayoutredeem'),
    ]

    operations = [
        migrations.AddField(
            model_name='executivepayoutredeem',
            name='account_number',
            field=models.CharField(blank=True, help_text='Account number for payment', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='executivepayoutredeem',
            name='ifsc_code',
            field=models.CharField(blank=True, help_text='IFSC code for payment', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='executivepayoutredeem',
            name='upi_details',
            field=models.CharField(blank=True, help_text='UPI details for payment', max_length=255, null=True),
        ),
    ]
