# Generated by Django 5.1.4 on 2025-10-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_executivepayoutredeem_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecharge',
            name='by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
