# Generated by Django 5.1.4 on 2025-10-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_userrecharge_by_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecharge',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='userrecharge',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userrecharge',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userrecharge',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userrecharge',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userrecharge',
            name='is_successful',
            field=models.BooleanField(default=False),
        ),
    ]
