# Generated by Django 6.0.1 on 2026-01-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_userrecharge_payment_status_and_more'),
        ('users', '0013_userprofile_fcm_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('payload', models.JSONField()),
                ('signature', models.CharField(blank=True, max_length=512, null=True)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='userrecharge',
            name='notes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userrecharge',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userrecharge',
            name='webhook_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userrecharge',
            name='is_successful',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='userrecharge',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='userrecharge',
            name='razorpay_order_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='userrecharge',
            index=models.Index(fields=['payment_status', 'created_at'], name='payments_us_payment_b798c6_idx'),
        ),
        migrations.AddIndex(
            model_name='userrecharge',
            index=models.Index(fields=['user', 'payment_status'], name='payments_us_user_id_498f1a_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['event_type', 'processed'], name='payments_we_event_t_d02e9d_idx'),
        ),
    ]
