# Generated by Django 5.1.4 on 2025-08-12 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('dp_image', models.ImageField(blank=True, null=True, upload_to='user/dp_images/')),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=8, null=True)),
                ('coin_balance', models.PositiveIntegerField(default=0)),
                ('user_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_banned', models.BooleanField(default=False)),
                ('is_loginned', models.BooleanField(default=False)),
                ('is_suspended', models.BooleanField(default=False)),
                ('is_dormant', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_balance', models.PositiveIntegerField(default=0)),
                ('total_calls', models.PositiveIntegerField(default=0)),
                ('total_call_seconds', models.PositiveIntegerField(default=0)),
                ('total_call_seconds_today', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='users.userprofile')),
            ],
        ),
    ]
