# Generated by Django 5.1.4 on 2025-08-12 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofileoutstandingtoken_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='userprofile',
        ),
        migrations.AlterModelTable(
            name='userprofileblacklistedtoken',
            table='userprofile_blacklisted_token',
        ),
        migrations.AlterModelTable(
            name='userprofileoutstandingtoken',
            table='userprofile_outstanding_token',
        ),
    ]
