# Generated by Django 5.1.4 on 2025-08-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_carouselimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimage',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
