# Generated by Django 5.1.4 on 2025-09-25 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_carouselimage_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='coin_balance',
        ),
    ]
