# Generated by Django 5.1.4 on 2025-10-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_userprofile_coin_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimage',
            name='for_executive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='for_user',
            field=models.BooleanField(default=False),
        ),
    ]
