# Generated by Django 5.1.4 on 2025-08-18 06:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('executives', '0007_blockedusersbyexecutive'),
        ('users', '0010_alter_carouselimage_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgoraCallHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('token', models.CharField(max_length=512)),
                ('executive_token', models.CharField(max_length=512)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ringing', 'Ringing'), ('joined', 'Joined'), ('missed', 'Missed'), ('ended', 'Ended'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('uid', models.IntegerField()),
                ('callee_uid', models.IntegerField(blank=True, null=True)),
                ('coins_deducted', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('coins_added', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('last_coin_update_time', models.DateTimeField(blank=True, null=True)),
                ('ended_by', models.CharField(blank=True, max_length=50, null=True)),
                ('end_request_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('executive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agora_calls_received', to='executives.executive')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agora_calls_made', to='users.userprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', 'channel_name'], name='calls_agora_is_acti_e06bd8_idx'), models.Index(fields=['status'], name='calls_agora_status_d833e4_idx')],
            },
        ),
    ]
