# Generated by Django 5.1.4 on 2025-08-23 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
        ('executives', '0007_blockedusersbyexecutive'),
        ('users', '0010_alter_carouselimage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agoracallhistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ringing', 'Ringing'), ('joined', 'Joined'), ('missed', 'Missed'), ('ended', 'Ended'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='CallRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('execallhistory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='calls.agoracallhistory')),
                ('executive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_ratings', to='executives.executive')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_ratings', to='users.userprofile')),
            ],
        ),
    ]
