# Generated by Django 5.1.4 on 2025-09-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_alter_agoracallhistory_status_callrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agoracallhistory',
            name='coins_added',
        ),
        migrations.AddField(
            model_name='agoracallhistory',
            name='amount_per_min',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='agoracallhistory',
            name='coins_per_second',
            field=models.FloatField(default=3),
        ),
        migrations.AddField(
            model_name='agoracallhistory',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agoracallhistory',
            name='executive_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
