# Generated by Django 5.1.4 on 2025-09-25 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_remove_agoracallhistory_coins_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agoracallhistory',
            name='amount_per_min',
        ),
        migrations.RemoveField(
            model_name='agoracallhistory',
            name='coins_per_second',
        ),
        migrations.RemoveField(
            model_name='agoracallhistory',
            name='duration_seconds',
        ),
        migrations.RemoveField(
            model_name='agoracallhistory',
            name='executive_earnings',
        ),
        migrations.AddField(
            model_name='agoracallhistory',
            name='coins_added',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
