# Generated by Django 5.1.4 on 2025-09-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0004_remove_agoracallhistory_amount_per_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agoracallhistory',
            name='coins_per_second',
            field=models.FloatField(default=3),
        ),
    ]
