# Generated by Django 5.1.4 on 2025-09-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0005_agoracallhistory_coins_per_second'),
    ]

    operations = [
        migrations.AddField(
            model_name='agoracallhistory',
            name='amount_per_min',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
