# Generated by Django 5.1.4 on 2025-09-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0006_agoracallhistory_amount_per_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='agoracallhistory',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agoracallhistory',
            name='executive_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
