# Generated by Django 5.1.4 on 2025-10-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0007_agoracallhistory_duration_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agoracallhistory',
            name='status',
            field=models.CharField(choices=[('calling', 'calling'), ('ringing', 'Ringing'), ('joined', 'Joined'), ('missed', 'Missed'), ('ended', 'Ended'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=10),
        ),
    ]
