# Generated by Django 5.1.4 on 2025-10-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0008_alter_agoracallhistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agoracallhistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ringing', 'Ringing'), ('joined', 'Joined'), ('missed', 'Missed'), ('ended', 'Ended'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=10),
        ),
    ]
