# Generated by Django 5.1.4 on 2025-10-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0009_alter_agoracallhistory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agoracallhistory',
            name='is_monitored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agoracallhistory',
            name='monitor_token',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='agoracallhistory',
            name='monitor_uid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agoracallhistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ringing', 'Ringing'), ('joined', 'Joined'), ('missed', 'Missed'), ('ended', 'Ended'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='ringing', max_length=10),
        ),
    ]
