# Generated by Django 6.0.1 on 2026-07-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0010_agoracallhistory_is_monitored_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agoracallhistory',
            name='presence_missed_since',
            field=models.DateTimeField(blank=True, help_text="First time the Agora presence check found neither party in the channel; only ends the call once this has held for a confirm window, so one momentary blip doesn't kill a healthy call.", null=True),
        ),
    ]
