# Generated by Django 6.0.1 on 2026-07-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0011_agoracallhistory_presence_missed_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='agoracallhistory',
            name='presence_partial_since',
            field=models.DateTimeField(blank=True, help_text="First time the Agora presence check found exactly ONE party still in the channel (the other left/crashed but this side's app kept the RTC session alive in the background); ends the call once this has held for a confirm window.", null=True),
        ),
    ]
