# Generated by Django 6.0.1 on 2026-09-02 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0012_agoracallhistory_presence_partial_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='agoracallhistory',
            name='executive_joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agoracallhistory',
            name='executive_left_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agoracallhistory',
            name='hangup_reason',
            field=models.CharField(blank=True, help_text='Why the call ended: an Agora-reported leave reason when available, otherwise a fallback derived from ended_by (e.g. user_ended, executive_ended, system_timeout).', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agoracallhistory',
            name='talk_overlap_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Seconds both parties were actually present together, computed from user/executive joined/left timestamps. Reporting only — does not affect billing.', null=True),
        ),
        migrations.AddField(
            model_name='agoracallhistory',
            name='user_joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agoracallhistory',
            name='user_left_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
