# Generated by Django 5.1.4 on 2025-08-12 04:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('executive_id', models.CharField(max_length=20, unique=True)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(default='Guest', max_length=100)),
                ('age', models.PositiveIntegerField(default=18)),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(default='unspecified', max_length=20)),
                ('profession', models.CharField(default='Not Provided', max_length=100)),
                ('skills', models.TextField(blank=True)),
                ('place', models.CharField(blank=True, max_length=100)),
                ('education_qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('on_call', models.BooleanField(default=False)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('online', models.BooleanField(default=False)),
                ('is_suspended', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
                ('is_logged_out', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('device_id', models.CharField(default=uuid.uuid4, max_length=255)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('manager_executive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_executives', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExecutiveStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins_per_second', models.FloatField(default=3)),
                ('set_coin', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_on_duty_seconds', models.PositiveIntegerField(default=0)),
                ('total_talk_seconds_today', models.PositiveIntegerField(default=0)),
                ('total_picked_calls', models.PositiveIntegerField(default=0)),
                ('total_missed_calls', models.PositiveIntegerField(default=0)),
                ('coin_balance', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('executive', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='executives.executive')),
            ],
        ),
    ]
