# Generated by Django 5.1.4 on 2025-08-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executive',
            name='is_logged_out',
            field=models.BooleanField(default=False),
        ),
    ]
