# Generated by Django 5.1.4 on 2025-08-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0002_alter_executive_is_logged_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
