# Generated by Django 5.1.4 on 2025-08-12 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0003_executive_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutiveToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('executive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='executives.executive')),
            ],
        ),
    ]
