# Generated by Django 5.1.4 on 2025-08-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0004_executivetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive',
            name='is_offline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='executive',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
