# Generated by Django 5.1.4 on 2025-08-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0005_executive_is_offline_executive_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
