# Generated by Django 5.1.4 on 2025-08-13 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0006_executive_is_deleted'),
        ('users', '0005_alter_userprofile_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedusersByExecutive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_blocked', models.BooleanField(default=False)),
                ('reason', models.TextField()),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('executive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_executives', to='executives.executive')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to='users.userprofile')),
            ],
            options={
                'unique_together': {('user', 'executive')},
            },
        ),
    ]
