# Generated by Django 5.1.4 on 2025-09-20 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0007_blockedusersbyexecutive'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutiveProfilePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(upload_to='executive_pictures/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('executive', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='executives.executive')),
            ],
        ),
    ]
