# Generated by Django 5.1.4 on 2025-09-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0008_executiveprofilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executive',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
