# Generated by Django 5.1.4 on 2025-09-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0009_alter_executive_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executive',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
