# Generated by Django 5.1.4 on 2025-09-23 07:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0010_alter_executive_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='executivetoken',
            name='access_token',
            field=models.CharField(default='000', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='executivetoken',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
