# Generated by Django 5.1.4 on 2025-09-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0011_executivetoken_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
