# Generated by Django 5.1.4 on 2025-09-24 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0012_executive_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executive',
            name='is_approved',
        ),
    ]
