# Generated by Django 5.1.4 on 2025-09-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0013_remove_executive_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='executive',
            name='languages_known',
            field=models.ManyToManyField(blank=True, related_name='executives', to='executives.language'),
        ),
    ]
