# Generated by Django 5.1.4 on 2025-09-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0014_language_executive_languages_known'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive',
            name='amount_per_minute',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Rate per minute decided by admin', max_digits=10),
        ),
    ]
