# Generated by Django 5.1.4 on 2025-09-25 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0015_executive_amount_per_minute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executive',
            name='amount_per_minute',
        ),
    ]
