# Generated by Django 5.1.4 on 2025-09-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0016_remove_executive_amount_per_minute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='executivestats',
            old_name='set_coin',
            new_name='amount_per_min',
        ),
        migrations.RenameField(
            model_name='executivestats',
            old_name='coin_balance',
            new_name='vault_Balance',
        ),
        migrations.AddField(
            model_name='executivestats',
            name='earnings_today',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Earnings for today', max_digits=12),
        ),
        migrations.AddField(
            model_name='executivestats',
            name='pending_payout',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Balance to be paid to executive', max_digits=12),
        ),
        migrations.AddField(
            model_name='executivestats',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total lifetime earnings of executive', max_digits=12),
        ),
    ]
