# Generated by Django 5.1.4 on 2025-09-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0017_rename_set_coin_executivestats_amount_per_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
