# Generated by Django 5.1.4 on 2025-09-30 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0018_executive_is_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='executive',
            old_name='is_favorite',
            new_name='is_favourite',
        ),
    ]
