# Generated by Django 5.1.4 on 2025-10-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0019_rename_is_favorite_executive_is_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='executivestats',
            name='earnings_today',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Earnings for current day (auto-resets daily)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='executivestats',
            name='pending_payout',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Lifetime payout pending (does not reset daily)', max_digits=12),
        ),
    ]
