# Generated by Django 5.1.4 on 2025-10-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0020_executive_fcm_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='executivestats',
            name='total_talk_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
