# Generated by Django 6.0.1 on 2026-03-05 06:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0021_executivestats_total_talk_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_amount_per_min', models.DecimalField(decimal_places=2, default=2.0, help_text='Default global rate per minute for executives', max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Pricing',
                'verbose_name_plural': 'Global Pricing',
            },
        ),
        migrations.CreateModel(
            name='RateSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for the schedule', max_length=100)),
                ('amount_per_min', models.DecimalField(decimal_places=2, help_text='Rate per minute during this schedule', max_digits=10)),
                ('start_time', models.TimeField(blank=True, help_text='Start time (optional, if null applies all day)', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='End time (optional, if null applies all day)', null=True)),
                ('days_of_week', models.JSONField(blank=True, default=list, help_text='List of day numbers 0-6 (Monday=0), empty means all days')),
                ('active', models.BooleanField(default=True, help_text='Whether this schedule is active')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher priority wins in overlaps')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rate Schedule',
                'verbose_name_plural': 'Rate Schedules',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.AddField(
            model_name='executive',
            name='use_personal_rate',
            field=models.BooleanField(default=False, help_text='If true, use personal amount_per_min instead of global rates'),
        ),
        migrations.AlterField(
            model_name='executivestats',
            name='amount_per_min',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=10),
        ),
    ]
