# Generated by Django 6.0.1 on 2026-03-05 06:26

from django.db import migrations
from decimal import Decimal


def create_initial_pricing_data(apps, schema_editor):
    """
    Create initial GlobalPricing and RateSchedule data.
    """
    GlobalPricing = apps.get_model('executives', 'GlobalPricing')
    RateSchedule = apps.get_model('executives', 'RateSchedule')
    ExecutiveStats = apps.get_model('executives', 'ExecutiveStats')
    
    # Get the earliest existing amount_per_min or default to 2.0
    try:
        earliest_rate = ExecutiveStats.objects.order_by('id').first()
        default_rate = earliest_rate.amount_per_min if earliest_rate else Decimal('2.0')
    except:
        default_rate = Decimal('2.0')
    
    # Create GlobalPricing
    GlobalPricing.objects.get_or_create(
        defaults={'default_amount_per_min': default_rate}
    )
    
    # Create default RateSchedule
    RateSchedule.objects.get_or_create(
        name="Default Schedule",
        defaults={
            'amount_per_min': default_rate,
            'active': True,
            'priority': 0,
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0022_globalpricing_rateschedule_and_more'),
    ]

    operations = [
        migrations.RunPython(create_initial_pricing_data),
    ]
