# Generated by Django 6.0.1 on 2026-06-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0023_create_initial_pricing_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
