# Generated by Django 6.0.1 on 2026-07-02 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0024_add_username_to_executive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executiveprofilepicture',
            name='executive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_pictures', to='executives.executive'),
        ),
    ]
