# Generated by Django 6.0.1 on 2026-07-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0025_alter_executiveprofilepicture_executive'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive',
            name='is_phone_verified',
            field=models.BooleanField(default=False, help_text='Mobile number confirmed via OTP at registration'),
        ),
    ]
