# Generated by Django 6.0.1 on 2026-07-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0027_executivependingregistrationotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutivePasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(db_index=True, max_length=15)),
                ('otp_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
