# Generated by Django 5.1.4 on 2025-08-12 04:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15, null=True, unique=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('otp_attempts', models.PositiveSmallIntegerField(default=0)),
                ('otp_verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.CharField(choices=[('hr_user', 'HR - User'), ('hr_executive', 'HR - Executive'), ('manager_user', 'Manager - User'), ('manager_executive', 'Manager - Executive'), ('superuser', 'Superuser'), ('other', 'Other')], default='other', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, related_name='admin_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='admin_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
