# Generated by Django 5.2.6 on 2025-09-29 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(blank=True, max_length=255)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('jwt_jti', models.CharField(db_index=True, max_length=255, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Session',
                'verbose_name_plural': 'Admin Sessions',
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['admin', 'is_active'], name='accounts_ad_admin_i_a9abca_idx'), models.Index(fields=['jwt_jti'], name='accounts_ad_jwt_jti_ff1f4a_idx')],
            },
        ),
    ]
