# Generated by Django 5.1.4 on 2025-10-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_adminsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='custom_permissions',
            field=models.JSONField(blank=True, default=list, help_text='Stores specific functions or access privileges this admin can use'),
        ),
    ]
